# Generated by Django 4.0.4 on 2022-05-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_questiontype_section_course_alter_course_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_slug',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='question_slug',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
