# Generated by Django 4.0.4 on 2022-05-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_course_course_slug_question_question_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question',
            field=models.TextField(default=0, max_length=300),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questiontype',
            name='type',
            field=models.CharField(max_length=10, verbose_name='Type'),
        ),
    ]
